webtalk_init -webtalk_dir D:/program/Vivado/Project/ip_ram/ip_ram/ip_ram.sim/sim_1/behav/xsim/xsim.dir/tb_kara_mult_ram_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Sep  8 21:02:52 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "05e2f34b-9f58-4e92-9cbd-894f14944db4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "11abf5256ec14bdf9dbb527fd6d0d1e2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "80" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "334195 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "3.41_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15592_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2572179365 -regid "" -xml D:/program/Vivado/Project/ip_ram/ip_ram/ip_ram.sim/sim_1/behav/xsim/xsim.dir/tb_kara_mult_ram_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/program/Vivado/Project/ip_ram/ip_ram/ip_ram.sim/sim_1/behav/xsim/xsim.dir/tb_kara_mult_ram_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/program/Vivado/Project/ip_ram/ip_ram/ip_ram.sim/sim_1/behav/xsim/xsim.dir/tb_kara_mult_ram_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
