# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/program/Vivado/Project/ip_ram/ip_ram/ip_ram.srcs/sources_1/ip/ram_dual/ram_dual.xci
# IP: The module: 'ram_dual' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/program/Vivado/Project/ip_ram/ip_ram/ip_ram.srcs/sources_1/ip/ram_dual/ram_dual_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_dual'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/program/Vivado/Project/ip_ram/ip_ram/ip_ram.srcs/sources_1/ip/ram_dual/ram_dual.xci
# IP: The module: 'ram_dual' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/program/Vivado/Project/ip_ram/ip_ram/ip_ram.srcs/sources_1/ip/ram_dual/ram_dual_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_dual'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
