######################################################################
#
# File name : tb_kara_mult_ram.udo
# Created on: Tue Sep 08 21:03:03 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
