######################################################################
#
# File name : tb_kara_mult_ram_compile.do
# Created on: Wed Sep 16 00:41:13 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/blk_mem_gen_v8_4_2
vlib modelsim_lib/msim/xil_defaultlib
vlib modelsim_lib/msim/xbip_utils_v3_0_9
vlib modelsim_lib/msim/xbip_pipe_v3_0_5
vlib modelsim_lib/msim/xbip_bram18k_v3_0_5
vlib modelsim_lib/msim/mult_gen_v12_0_14

vmap blk_mem_gen_v8_4_2 modelsim_lib/msim/blk_mem_gen_v8_4_2
vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
vmap xbip_utils_v3_0_9 modelsim_lib/msim/xbip_utils_v3_0_9
vmap xbip_pipe_v3_0_5 modelsim_lib/msim/xbip_pipe_v3_0_5
vmap xbip_bram18k_v3_0_5 modelsim_lib/msim/xbip_bram18k_v3_0_5
vmap mult_gen_v12_0_14 modelsim_lib/msim/mult_gen_v12_0_14

vlog -64 -incr -work blk_mem_gen_v8_4_2  \
"../../../../ip_ram.ip_user_files/ipstatic/simulation/blk_mem_gen_v8_4.v" \

vlog -64 -incr -work xil_defaultlib  \
"../../../../ip_ram.srcs/sources_1/ip/ram_dual/sim/ram_dual.v" \

vcom -64 -93 -work xbip_utils_v3_0_9  \
"../../../../ip_ram.ip_user_files/ipstatic/hdl/xbip_utils_v3_0_vh_rfs.vhd" \

vcom -64 -93 -work xbip_pipe_v3_0_5  \
"../../../../ip_ram.ip_user_files/ipstatic/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \

vcom -64 -93 -work xbip_bram18k_v3_0_5  \
"../../../../ip_ram.ip_user_files/ipstatic/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \

vcom -64 -93 -work mult_gen_v12_0_14  \
"../../../../ip_ram.ip_user_files/ipstatic/hdl/mult_gen_v12_0_vh_rfs.vhd" \

vcom -64 -93 -work xil_defaultlib  \
"../../../../ip_ram.srcs/sources_1/ip/mult_signed_18bit/sim/mult_signed_18bit.vhd" \

vlog -64 -incr -work xil_defaultlib  \
"../../../../ip_ram.srcs/sources_1/new/kara_mult_34bit.v" \
"../../../../ip_ram.srcs/sources_1/new/kara_mult_66bit.v" \
"../../../../ip_ram.srcs/sources_1/new/kara_mult_ram_top.v" \
"../../../../ip_ram.srcs/sources_1/new/karatsuba_top.v" \

vlog -64 -incr -sv -work xil_defaultlib  \
"../../../../ip_ram.srcs/sources_1/new/srl_lut.sv" \

vlog -64 -incr -work xil_defaultlib  \
"../../../../ip_ram.srcs/sim_1/new/tb_kara_mult_ram.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

