######################################################################
#
# File name : tb_kara_mult_ram_simulate.do
# Created on: Wed Sep 16 00:41:19 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L blk_mem_gen_v8_4_2 -L xil_defaultlib -L xbip_utils_v3_0_9 -L xbip_pipe_v3_0_5 -L xbip_bram18k_v3_0_5 -L mult_gen_v12_0_14 -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_kara_mult_ram xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_kara_mult_ram_wave.do}

view wave
view structure
view signals

log -r /*

do {tb_kara_mult_ram.udo}

run 6000ns
