######################################################################
#
# File name : tb_kara_mult_ram_wave.do
# Created on: Tue Sep 08 21:03:03 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
