# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/work/ESLAS_prj/LAB_BRAM/ip_ram/ip_ram.srcs/sources_1/ip/mult_ram/mult_ram.xci
# IP: The module: 'mult_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/work/ESLAS_prj/LAB_BRAM/ip_ram/ip_ram.srcs/sources_1/ip/mult_ram/mult_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/work/ESLAS_prj/LAB_BRAM/ip_ram/ip_ram.srcs/sources_1/ip/mult_ram/mult_ram.xci
# IP: The module: 'mult_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/work/ESLAS_prj/LAB_BRAM/ip_ram/ip_ram.srcs/sources_1/ip/mult_ram/mult_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
